k9s:
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  headless: false
  logoless: false
  crumbsless: false
  readOnly: false
  noIcons: true
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 60
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: internal
  currentCluster: internal
  clusters:
    adp-staging:
      namespace:
        active: argocd
        favorites:
        - argocd
        - all
        - default
      view:
        active: pod argocd
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    asp:
      namespace:
        active: cattle-monitoring-system
        favorites:
        - cattle-monitoring-system
        - lufthansa-customer
        - default
      view:
        active: po cattle-monitoring-system
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    gke_ad-itdevmore-prod-platform-de_europe-west3-a_ci:
      namespace:
        active: concourse-deployment
        favorites:
        - monitoring
        - all
        - concourse-deployment
        - default
      view:
        active: sec
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    gke_asp-staging_europe-west1-b_sandbox:
      namespace:
        active: staging
        favorites:
        - staging
        - default
      view:
        active: pod
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    internal:
      namespace:
        active: default
        favorites:
        - default
      view:
        active: po
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    local:
      namespace:
        active: cattle-system
        favorites:
        - cattle-system
        - default
      view:
        active: po cattle-system
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    prod:
      namespace:
        active: ""
        favorites:
        - all
        - default
      view:
        active: po default
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    sandbox:
      namespace:
        active: default
        favorites:
        - default
      view:
        active: po
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    usu-integration:
      namespace:
        active: cert-manager
        favorites:
        - mariadb
        - all
        - cert-manager
        - default
      view:
        active: pods cert-manager
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
