# View user-supplied values when the helm chart was created

plugin:
  helm-values:
    shortCut: v
    confirm: false
    description: Values
    scopes:
    - helm
    command: sh
    background: false
    args:
    - -c
    - "helm get values $COL-NAME -n $NAMESPACE --kube-context $CONTEXT | less"

  toggle-helmrelease:
    shortCut: Shift-T
    confirm: true
    scopes:
      - helmreleases
    description: Toggle to suspend or resume a HelmRelease
    command: sh
    background: false
    args:
      - -c
      - "flux $([ $(kubectl get helmreleases -n $NAMESPACE $NAME -o=custom-columns=TYPE:.spec.suspend | tail -1) = \"true\" ] && echo \"resume\" || echo \"suspend\") helmrelease -n $NAMESPACE $NAME | less"
  toggle-kustomization:
    shortCut: Shift-T
    confirm: true
    scopes:
      - kustomizations
    description: Toggle to suspend or resume a Kustomization
    command: sh
    background: false
    args:
      - -c
      - "flux $([ $(kubectl get kustomizations -n $NAMESPACE $NAME -o=custom-columns=TYPE:.spec.suspend | tail -1) = \"true\" ] && echo \"resume\" || echo \"suspend\") kustomization -n $NAMESPACE $NAME | less"
  reconcile-git:
    shortCut: Shift-R
    confirm: false
    description: Flux reconcile
    scopes:
    - gitrepositories
    command: sh
    background: false
    args:
    - -c
    - "flux reconcile source git -n $NAMESPACE $NAME | less"
  reconcile-hr:
    shortCut: Shift-R
    confirm: false
    description: Flux reconcile
    scopes:
    - helmreleases
    command: sh
    background: false
    args:
    - -c
    - "flux reconcile helmrelease -n $NAMESPACE $NAME --with-source | less"
  reconcile-ks:
    shortCut: Shift-R
    confirm: false
    description: Flux reconcile
    scopes:
    - kustomizations
    command: sh
    background: false
    args:
    - -c
    - "flux reconcile kustomization -n $NAMESPACE $NAME --with-source | less"
  getall-ns:
    shortCut: Shift-G
    confirm: false
    description: Get All Resources in NS
    scopes:
    - namespaces
    command: sh
    background: false
    args:
    - -c
    - "kubectl get all -n $NAME | less"
